version: '3.9'

volumes:
  bot_data:

services:
  redditbot:
    container_name: redditbot-container
    env_file: .env
    image: ${DOCKER_LOGIN}/redditbot
    restart: always
    volumes:
      - bot_data:/app/
    environment:
      TZ: Asia/Shanghai