version: '3.9'

volumes:
  bot_data:

services:
  redditbot:
    container_name: redditbot-container
    env_file: .env
    image: ${DOCKER_LOGIN}/redditbot
    command: python3 -m bot
    restart: always
    volumes:
      - bot_data:/app/